Update workflow

diff --git a/.github/workflows/sec-sca-githubactionsversionupdater.yml b/.github/workflows/sec-sca-githubactionsversionupdater.yml
--- a/.github/workflows/sec-sca-githubactionsversionupdater.yml
+++ b/.github/workflows/sec-sca-githubactionsversionupdater.yml
@@ -15,9 +15,11 @@ jobs:
 
     steps:
       - name: Ensure workflow secret is configured
-        if: ${{ secrets.WORKFLOW_SECRET == '' }}
         run: |
-          echo "::error::The WORKFLOW_SECRET secret is not configured."
+          if [ -z "${{ secrets.WORKFLOW_SECRET }}" ]; then
+            echo "::error::The WORKFLOW_SECRET secret is not configured."
+            exit 1
+          fi
 
       - name: Checkout code
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
